version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cocos-challenge-db
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_SLDxY7hZMt3T
      POSTGRES_DB: neondb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U neondb_owner -d neondb"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: cocos-challenge
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=neondb_owner
      - DATABASE_PASSWORD=npg_SLDxY7hZMt3T
      - DATABASE_NAME=neondb
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: